# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    increment_build_number(xcodeproj: "/Users/junekim/Documents/Splice/Shortn.xcodeproj")
    build_app(workspace: "Shortn.xcworkspace", scheme: "Shortn")
    upload_to_app_store
  end
end
